FROM node:16.10.0-alpine3.11

# Create Directory for the Container
WORKDIR /app
COPY . .

# Run npm and install modules
RUN npm i

# Expose application port
EXPOSE 4000

# Run start command
CMD ["npm", "run", "start:dev"]
